style(client): format python code and apply flake8 suggestions
I ran precommit and fixed the issue that came up.
Precommit run before this commit :
```
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted server/tools/gen_enclave_info_toml.py
reformatted tests/test_distilbert.py
reformatted tests/test_covidnet.py
reformatted client/setup.py
reformatted client/tests/test_requests.py
reformatted client/blindai/client.py

All done! ✨ 🍰 ✨
6 files reformatted, 13 files left unchanged.

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

client/tests/test_requests.py:12:1: F811 redefinition of unused 'time' from line 4
client/tests/test_proof.py:24:13: F405 'Mock' may be undefined, or defined from star imports: unittest.mock
client/tests/test_proof.py:35:6: F405 'patch' may be undefined, or defined from star imports: unittest.mock
client/tests/test_proof.py:68:6: F405 'patch' may be undefined, or defined from star imports: unittest.mock
client/tests/test_proof.py:98:6: F405 'patch' may be undefined, or defined from star imports: unittest.mock
client/tests/test_proof.py:175:6: F405 'patch' may be undefined, or defined from star imports: unittest.mock
client/blindai/client.py:39:1: F811 redefinition of unused 'SendModelRequest' from line 39
client/blindai/client.py:39:1: F811 redefinition of unused 'RunModelRequest' from line 39
client/blindai/client.py:39:1: F811 redefinition of unused 'Payload' from line 39

fmt......................................................................Passed
```